version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ai-task-manager/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
  - package-ecosystem: "pip"
    directory: "/ai-task-manager/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
