services:
  - type: web
    name: ai-task-manager-backend
    rootDir: ai-task-manager/backend
    env: python
    plan: free
    region: oregon
    pythonVersion: 3.11.7
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
