name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  secret-scan:
    name: Secret Scan (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "detect --source . --no-banner"

  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: ai-task-manager/frontend
        run: yarn install --frozen-lockfile

      - name: Run yarn audit
        working-directory: ai-task-manager/frontend
        run: |
          yarn audit --groups dependencies --severity moderate

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install safety
        run: |
          python -m pip install --upgrade pip
          pip install safety==3.2.4

      - name: Run safety on backend requirements
        run: |
          safety check --file ai-task-manager/backend/requirements.txt --full-report
